spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/identity_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expiry-seconds: ${JWT_EXPIRY_SECONDS}

outbound:
  identity:
    client-id: ${IDENTITY_CLIENT_ID}
    client-secret: ${IDENTITY_CLIENT_SECRET}
    redirect-uri: ${IDENTITY_REDIRECT_URI}
    grant_type: authorization_code