services:
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - qwertymech-net

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - qwertymech-net

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=qwertymech
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - qwertymech-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    hostname: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - identity-service
      - product-service
      - cart-service
      - order-service
      - payment-service
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8082
      - CART_SERVICE_URL=http://cart-service:8083
      - ORDER_SERVICE_URL=http://order-service:8084
      - PAYMENT_SERVICE_URL=http://payment-service:8085
    networks:
      - qwertymech-net

  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service
    hostname: identity-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
    env_file:
      - ./identity-service/.env
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/identity_service
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - qwertymech-net

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    hostname: product-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/product_service
    networks:
      - qwertymech-net

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    hostname: cart-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - product-service
      - identity-service
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/cart_service
      - IDENTITY_SERVICE_URL=http://identity-service:8081/identity
      - PRODUCT_SERVICE_URL=http://product-service:8082/product
    networks:
      - qwertymech-net

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    hostname: order-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - kafka
      - redis
      - identity-service
      - product-service
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/order_service
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HORT=redis
      - IDENTITY_SERVICE_URL=http://identity-service:8081/identity
      - PRODUCT_SERVICE_URL=http://product-service:8082/product
    networks:
      - qwertymech-net

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    hostname: payment-service
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - order-service
    env_file:
      - ./payment-service/.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORDER_SERVICE_URL=http://order-service:8084
    networks:
      - qwertymech-net

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    hostname: notification-service
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - kafka
    env_file:
      - ./notification-service/.env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - qwertymech-net

networks:
  qwertymech-net:
    driver: bridge
