server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: ${app.services.identity}
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                - StripPrefix=2
            - id: product-service
              uri: ${app.services.product}
              predicates:
                - Path=${app.api-prefix}/product/**
              filters:
                - StripPrefix=2
            - id: cart-service
              uri: ${app.services.cart}
              predicates:
                - Path=${app.api-prefix}/cart/**
              filters:
                - StripPrefix=2

app:
  api-prefix: /api/v1
  services:
    identity: ${IDENTITY_SERVICE_URL:http://localhost:8081}
    product: ${PRODUCT_SERVICE_URL:http://localhost:8082}
    cart: ${CART_SERVICE_URL:http://localhost:8083}
