server:
  port: 8083
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cart_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

app:
  services:
    identity: ${IDENTITY_SERVICE_URL:http://localhost:8081/identity}
    product: ${PRODUCT_SERVICE_URL:http://localhost:8082/product}